### ISSUE TITLE
Про приложение

### ISSUE THREAD

**Issue by avsym** [MartSlaaf/UIR_template#1]
Должно быть по середине: Приложение Буква_приложния
С новой строки по середине: Название_приложения

ГОСТ отсюда: http://mephi17.ru/index.php?action=files&step=download&id=70

**Comment by MartSlaaf** [comment]
Вестимо, пока петух не клюнул, оно и не проклевывалось.
По центру, как я посмотрел - не обязательно, можно делать как если бы это был обычный раздел. Так и написал пока. Может позже отцентрую.
